send_message/main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth.views import LogoutView

from .views import *

app_name = 'main'

urlpatterns = [
    url(r'^$', MainPage.as_view(), name='main_page'),
    url(r'^registration/(?P<pk>\d+)/$', RegisterUser.as_view(), name='registration'),
    url(r'^login/$', UserLogin.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^(?P<subscription_id>\d+)/(?P<user_id>\d+)/$', InSubscription.as_view(), name='insubs'),
    url(r'^(?P<subscription_id>\d+)/$', UnSubscription.as_view(), name='unsubs'),
    url(r'^send-happy/$', LayoutBD.as_view(), name='layout_bd'),
    url(r'^open-email/(?P<pk>\d+)/$', CheckEmail.as_view(), name="email_view"),
    url(r'^send-news/$', SendNews.as_view(), name='send_news'),
    url('^tasks/$', RenderTasks.as_view(), name='tasks'),
]

send_message/send_message/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

send_message/main/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
       Model representing a user.
    """
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    email = models.EmailField(unique=True, blank=True)
    birth_day = models.DateField(blank=True, null=True)
    subscriptions = models.ManyToManyField('Subscription', related_name='users')

    def __str__(self):
        """
        String for representing the User object (in Admin site etc.)
        """
        return self.get_full_name()





class Subscription(models.Model):
    """
    Model representing a subscription.
    """
    title = models.CharField(max_length=150)
    image = models.ImageField(upload_to='img/')


    def __str__(self):
        """
        String for representing the Subscription object (in Admin site etc.)
        """
        return self.title


class MailTrack(models.Model):
    """
    Model for tracking email
    """
    email = models.EmailField(max_length=254)
    view = models.BooleanField(default=False)

    def __str__(self):
        """
        String for representing MailTrack object (in Admin site etc.)
        """
        return self.email

send_message/main/forms.py
from django import forms
from .models import User
from django.contrib.auth import authenticate


class UserCreationForm(forms.Form):

    email = forms.EmailField(max_length=50, required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'id': "inputUsername"
    }))
    first_name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': "inputUsername"
    }))
    last_name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': "inputUsername"
    }))
    birth_day = forms.DateField(required=True, widget=forms.DateInput(attrs={
        'class': 'form-control',
        'id': "inputUsername"
    }))
    password = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'inputPassword',
    }))
    rep_password = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'ReInputPassword'
    }))

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['rep_password']
        if password != confirm_password:
            raise forms.ValidationError('Passwords did not match, please try again.')

    def save(self):
        del self.cleaned_data['rep_password']
        user = User(username=self.cleaned_data['email'],
                    email=self.cleaned_data['email'],
                    first_name=self.cleaned_data['first_name'],
                    last_name=self.cleaned_data['last_name'],
                    birth_day=self.cleaned_data['birth_day'],)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

class SignUser(forms.Form):
    email = forms.EmailField(max_length=50, required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'id': 'inputEmail',
        'placeholder': 'Email'
    }))
    password = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control mt-2',
        'id': 'inputPassword',
        'placeholder': 'Password'
    }))

send_message/main/views.py
from __future__ import unicode_literals

import os

from send_message import settings
from django.core.mail import EmailMessage
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.views import View
from django.contrib.auth import login, authenticate
from django.views.generic import ListView
from .models import Subscription, User, MailTrack
from .forms import UserCreationForm, SignUser
from .utils import MyMixin
from .tasks import send_registration_mail,send_subscribed_mail, send_unsubscribed_mail, send_hb_email, send_subs_email



class MainPage(ListView):
    """
    Display main page
    """

    model = Subscription
    template_name = 'main.html'
    context_object_name = 'subscriptions'


class RegisterUser(View):
    """
    Display the registration form
    """

    template_name = 'registration.html'

    def get(self, request, pk):
        return render(request, self.template_name, {'form': UserCreationForm()})

    def post(self, request, pk):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            subs = Subscription.objects.get(id=pk)
            user.subscriptions.add(subs)
            email = form.cleaned_data.get('email')
            try:
                send_registration_mail.delay(email, subs.title)
            except Exception as ex:
                HttpResponse(ex)
            return redirect('main:login')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

class UserLogin(View):
    """
    Display the login form
    """

    template_name = 'login.html'
    def get(self, request):
        form = SignUser()
        return render(request, self.template_name, {'form': form})

    def post(self,request):
        form = SignUser(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/')
        return render(request, self.template_name, {'form': form})

class InSubscription(View):
    """
    Subscription on news and send mail user
    """

    def post(self, request, subscription_id, user_id ):
        subscription = Subscription.objects.get(id=subscription_id)
        user = User.objects.get(id=user_id)
        user.subscriptions.add(subscription)
        user.save()
        send_subscribed_mail.delay(user.email, user.get_full_name(), subscription.title)
        return redirect('/')

class UnSubscription(View):
    """
    Unsubscription and send mail
    """

    def post(self, request, subscription_id):
        user = request.user
        subscription = Subscription.objects.get(id=subscription_id)
        user.subscriptions.remove(subscription)
        user.save()
        send_unsubscribed_mail.delay(user.email, user.get_full_name(), subscription.title)
        return redirect('/')


class LayoutBD(MyMixin, View):
    """
    Congratulations to users who have a birthday today.
    Template #1
    """
    def get(self, request):
        template = 'layouts/layout_BD.html'
        subject = 'birthday discount'
        for pk, full_name, birth_day, email in self.get_user_birth_info():
            context = {
                'full_name': full_name,
                'birth_day': birth_day,
                'image_url': settings.PROJECT_DOMAIN + '/open-email/?pk={}'.format(pk)
                }
            try:
                send_hb_email.delay(template, subject, email, context)
                new_track = MailTrack(email=email)
                new_track.save()
            except:
                return HttpResponse('Letters not sent to {}'.format(email))
        return HttpResponse('Letters sent')

class SendNews(MyMixin, View):
    """
    Send an email to the selected category
    """
    def post(self, request):
        template = 'layouts/subscription_layout.html'
        subject = 'News'
        cat_id = request.POST.get('section')
        for id, full_name, email in self.get_emails():
            section = Subscription.objects.get(pk=cat_id).title
            context = {
                'section': section,
                'full_name': full_name,
                'image_url': settings.PROJECT_DOMAIN + '/open-email/?pk={}'.format(id)
            }
            try:
                send_subs_email.delay(template, subject, email, context)
                # send_subs_email.apply_async((template, subject, email, context), countdown=60)
                new_track = MailTrack(email=email)
                new_track.save()
            except:
               return HttpResponse('email not send to {}'.format(email))
        return HttpResponse('All emails been sent')


class CheckEmail(View):
    """
    Checking the opening of the letter
    """
    def get(self, request, pk):
        email = User.objects.get(pk=pk).email
        check_status = MailTrack.objecst.get(email=email)
        check_status.view = True
        check_status.save()
        image = open(os.path.join('main', 'static/img/1x1.png'), 'rb').read()
        return HttpResponse(image, content_type='image/png')


class RenderTasks(View):
    """
    Dispaly task for staff
    """
    def get(self, request):
        return render(request, 'layouts/tasks.html')

send_message/main/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">


  </head>
  <body>

    {% block header %}{% endblock %}

    {% block content %}{% endblock %}



    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
  </body>
</html>

send_message/main/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}

{% block content %}
    <div class="text-center">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <form class="form-signin" method="post" action="">
            {% csrf_token %}
            <h1 class="h3 mb-3 mt-3 font-weight-normal">To login, enter:</h1>
            <div class="col-md-4 mb-3 mx-auto">
            <label for="inputUsername" class="sr-only">Email</label>
                {{ form.email }}</div>
            <div class="col-md-4 mb-3 mx-auto">
            <label for="inputPassword" class="sr-only">Password</label>
                {{ form.password }}</div>
            <div class="col-md-4 mb-3 mx-auto">
                <button class="btn mt-2 btn-lg btn-primary btn-block" type="submit">Login</button></div>
        </form>
    </div>
{% endblock %}

send_message/main/templates/main.html
{% extends 'base.html' %}
{% block title %}Main page{% endblock %}



{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if not user.is_authenticated %}
        <a href="{% url 'main:login' %}" class="btn btn-primary" role="button" style="position:absolute; top:5px; right:5px;">Login</a>
      {% else %}
        {% if user.is_staff %}
            <a href="{% url 'main:tasks' %}" class="btn btn-primary" role="button" style="position:absolute; top:5px; right:100px;">Send Email</a>
            <a href="{% url 'main:logout' %}" class="btn btn-primary" role="button" style="position:absolute; top:5px; right:5px;">Logout</a>
        {% else %}
            <a href="{% url 'main:logout' %}" class="btn btn-primary" role="button" style="position:absolute; top:5px; right:5px;">Logout</a>
        {% endif %}
      {% endif %}
  </div>
</nav>
<h1 style="text-align: center; margin-top: 20px; color: cadetblue">Welcome to the site "Useful mailing list"</h1>
<h3 style="text-align: center; margin-top: 10px">To receive news on the selected categories, you must register and subscribe to the desired news</h3>
<div class="card-deck" style="width: 90%; margin-top: 15px; margin-left: 5%">
{% for subs in subscriptions %}
  <div class="card">
    <img class="card-img-top" src="{{ subs.image.url }}" alt="{{ subs.title}}" width="349" height="180">
    <div class="card-body">
      <h5 class="card-title" style="text-align: center; color: darkseagreen">{{ subs.title }}</h5>
    </div>
    <div class="card-footer" style="text-align: center">
      {% if not user.is_authenticated %}
            <a href="{% url 'main:registration' subs.pk %}" class="btn btn-primary" role="button">Register and subscribe</a>
      {% endif %}
      {% if user.is_authenticated %}
              {% if subs in user.subscriptions.all %}
                <form action="{% url 'main:unsubs' subs.id %}" method="post">
                    {% csrf_token %}
                  <button class="btn btn-primary">UNSubscribe</button>
                </form>
                    {% else %}
                        <form action="{% url 'main:insubs' subs.id user.id %}" method="post">
                            {% csrf_token %}
                          <button class="btn btn-primary">Subscribe</button>
                        </form>
              {% endif %}
      {% endif %}
    </div>
  </div>
{% endfor %}
 </div>
{% endblock %}

send_message/main/templates/registration.html
{% extends 'base.html' %}
{% block title %}Registrations{% endblock %}

{% block content %}
    <div class="text-center">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <form class="form-signin" method="post" action="">
            {% csrf_token %}
            <h1 class="h3 mb-3 mt-3 font-weight-normal">Чтобы зарегестрироваться введите:</h1>
            <div class="col-md-4 mb-3 mx-auto">
            <label for="inputUsername">Email</label>
            {{ form.email }}
            </div>
            <div class="col-md-4 mb-3 mx-auto">
            <label for="inputUsername">Имя</label>
            {{ form.first_name }}
            </div>
            <div class="col-md-4 mb-3 mx-auto">
            <label for="inputUsername">Фамилия</label>
            {{ form.last_name }}
            </div>
            <div class="col-md-4 mb-3 mx-auto">
            <label for="inputUsername">Дата рождения</label>
            {{ form.birth_day }}
            </div>
            <div class="col-md-4 mb-3 mx-auto">
            <label for="inputUsername">Пароль:</label>
            {{ form.password }}
            </div>
            <div class="col-md-4 mb-3 mx-auto">
            <label for="inputUsername">Повторите пароль:</label>
            {{ form.rep_password }}
            </div>
            <div class="col-md-4 mb-3 mx-auto">
            <button class="btn mt-2 btn-lg btn-primary btn-block" type="submit">Регистрация</button>
            </div>
        </form>
    </div>
{% endblock %}